Contact/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web'))
]

web/urls.py
from django.urls import path
from . import views 


app_name = 'web'

urlpatterns = [
    path("",views.index, name='index'),
    path('users/', views.users, name='users'),
    path('set_delete/<int:user_id>/', views.set_delete, name='set_delete'),
]

web/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class user(models.Model):
    name = models.CharField(max_length=50)
    phone = models.PositiveIntegerField(
        validators=[MinLengthValidator(10)]
    )
    email = models.EmailField()
    is_delete = models.BooleanField(default=False)

web/views.py
from django.shortcuts import render , reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.http.response import HttpResponseRedirect

from .models import user

import pandas as pd


def clean_phone(phone):
    return ''.join(filter(str.isdigit, str(phone)))

def index(request):
    
    if request.method == 'POST' and request.FILES['myfile']:
        excel_file = request.FILES['myfile']
        df = pd.read_excel(excel_file)
        
        # Assuming 'Name', 'Phone', and 'Email' are required columns in the Excel sheet
        required_columns = ['Name', 'Phone', 'Email']
        
        # Check if all required columns exist in the Excel sheet
        if all(col in df.columns for col in required_columns):
            # Process the data and save it to your Django model
            for index, row in df.iterrows():
                name = row['Name']
                raw_phone = row['Phone'] 
                phone = clean_phone(raw_phone)  
                email = row['Email']
                
                # Create a new instance of the 'user' model and save it to the database
                new_user = user(name=name, phone=phone, email=email)
                new_user.save()
                
            # Data processing completed
            return HttpResponseRedirect("users")
        else:
            # Handle missing columns
            missing_columns = [col for col in required_columns if col not in df.columns]
            return HttpResponse(f"Missing columns: {missing_columns}", status=400)
    
    context = {
            "title":"Contact | Home",
    }
    return render(request, 'index.html', context=context) 

def users(request):
    users = user.objects.filter(is_delete=False)
    search = request.GET.get('search')
    if search:
        users = user.objects.filter(name__icontains=search)
    context = {
            "title":"Contact | users",
            "users":users,

    }
    
    return render(request,"users/users.html",context=context)


def set_delete(request, user_id): 
    user = get_object_or_404(User, id=user_id)  
    user.is_delete = True
    user.save()

    return HttpResponseRedirect(reverse('users'))

templates/index.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
        <title>{{title}}</title>
    </head>
    <body>
        <section id="main_page">
            <section class="home">
                <section class="left">
                    <div class="file_upload">
                        <h1>please upload your contacts file </h1>
                        <h2>(  file should be in .xlsx format and <br> should contain Name ,Phone and Email columns <br>in order )
                        </h2>
                        <form id="Upload_file" method="post" action="{% url 'web:index' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="file_upload">
                                <label for="myfile">File:</label>
                                <input type="file" id="myfile" name="myfile">
                            </div>
                            <div class="submit_button">
                                <input type="submit" value="upload">
                            </div>
                        </form>
                    </div>
                </section>
                <section class="right">
                    <div>
                        <img src="{% static 'images/home.jpg'%}" alt="">
                    </div>
                </section>
            </section>
        </section>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    </body>
</html>

templates/users/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{{title}}</title>
</head>
<body>
    <header>
        <h1>
            <div class="logo">
                <img src="{% static 'images/contacts.png'%}" alt="logo">
            </div>
            Contacts
        </h1>
        <div class="search">
            <form action="">
            {% csrf_token %}
                <div>
                    <img src="{% static 'images/search.png'%}" alt="">
                    <input type="text" name="search" id="search" placeholder="search">
                </div>
            </form>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'web:index' %}">Upload Another File</a></li>
            </ul>
            <div>
                <ul>
                    <li>
                        <a href="">
                            <img src="{% static 'images/profile.jpg'%}"  title="profile "  alt="profile image">
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <section id="contact">
        <div class="contact_table">
            <h1>Contacts (102)</h1>
            <div class="heading">
                <ul class="head">
                    <li>
                        <a href="">name</a>
                    </li>
                    <li>
                        <a href="">email</a>
                    </li>
                    
                </ul>
                <div class="line"></div>
                {% for user in users %}
                <ul class="contact-info" data-contact-id="{{ user.id }}">
                    <li>
                        <div>
                            <img src="{% static 'images/profile.jpg'%}" alt="">
                            <a href="">{{user.name}}</a>
                        </div>
                        
                    </li>
                    <li>
                        <a href="">{{user.email}}</a>
                    </li>
                    <li class="none" style="display: none;">
                        <a href="">{{user.phone}}</a>
                    </li>
                    <a href="{% url 'web:set_delete' user.id %}">
                        <!-- <img src="{% static 'images/delete.png'%}" alt=""> -->
                    </a>
                </ul>
                {% endfor %}
            </div>
        </div>
        <section id="right_side">
            <!-- Start of changes -->
            <div id="selected_user_details" style="display: none;">
                <div class="profile">
                    <img src="{% static 'images/profile.jpg'%}" alt="profile" id="profile_image">
                </div>
                <h2 id="selected_user_name"></h2>
                
                <div class="info">
                    <h3>Contact info :</h3>
                    <div class="phone_number">
                        <div class="Phone_icon">
                            <a href="#">
                                <img src="{% static 'images/call.png'%}" alt="">
                            </a>
                           <h5 id="selected_user_phone"></h5>
                           <div class="message_icon">
                                <a href="#">
                                     <img src="{% static 'images/message.png'%}" alt="">
                                </a>
                           </div>
                        </div>
                    </div>
                    <div class="email">
                        <div class="emial_icon">
                            <a href="#">
                                <img src="{% static 'images/email2.png'%}" alt="">
                            </a>
                           <h5 id="selected_user_email"></h5>
                           <div class="mail_icon">
                                <a href="#">
                                     <img src="{% static 'images/send_mail.png'%}" alt="">
                                </a>
                           </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of changes -->
        </section>
    </section>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>